services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: local-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodata:/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"

